#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./node_modules/.pnpm/@craigmiller160+js-config@1.0.4_@relmify+jest-fp-ts@2.1.1_@types+node@20.6.5_cross-env@7.0.3__4tl66yttwc6q3gaqwlebwsvlke/node_modules/lint-staged/bin/lint-staged.js --config ./node_modules/@craigmiller160/js-config/configs/lintstaged/.lintstagedrc